export function buildBodyMetricPayload(metric: Record<string, any>): Record<string, any> {
  return {
    date: metric.date,
    weight: metric.weight,
    body_fat_percentage: metric.bodyFatPercentage,
    muscle_mass: metric.muscleMass,
    measurements: metric.measurements,
    photo_urls: metric.photoUrls,
    heart_rate_rest: metric.heartRateRest || null,
    blood_pressure: metric.bloodPressure || null,
    sleep_quality: metric.sleepQuality || null,
    stress_level: metric.stressLevel || null,
    primary_goal: metric.primaryGoal || null,
    gender: metric.gender || null,
    age: metric.age || null,
    height: metric.height || null,
    activity_level: metric.activityLevel || null,
    tmb: metric.tmb || null,
    get: metric.get || null,
    lean_mass: metric.leanMass || null,
    fat_mass: metric.fatMass || null,
    met_activities: metric.metActivities || [],
    patient_profile: metric.patientProfile || null,
    calc_formula: metric.calcFormula || null,
    methodology_used: metric.methodologyUsed || null,
    injury_factor: metric.injuryFactor || 1.0,
    venta_target: metric.ventaTarget || null,
    target_weight: metric.targetWeight || null,
    days_for_goal: metric.daysForGoal || null,
    glucose: metric.glucose || null,
    sitting_height: metric.sittingHeight || null,
    knee_height: metric.kneeHeight || null,
    arm_relaxed_left: metric.armRelaxedLeft || null,
    arm_relaxed_right: metric.armRelaxedRight || null,
    arm_contracted_left: metric.armContractedLeft || null,
    arm_contracted_right: metric.armContractedRight || null,
    forearm_left: metric.forearmLeft || null,
    forearm_right: metric.forearmRight || null,
    wrist_circ_left: metric.wristCircLeft || null,
    wrist_circ_right: metric.wristCircRight || null,
    neck_circ: metric.neckCirc || null,
    shoulder_circ: metric.shoulderCirc || null,
    chest_circ: metric.chestCirc || null,
    waist_circ: metric.waistCirc || null,
    abdomen_circ: metric.abdomenCirc || null,
    hip_circ: metric.hipCirc || null,
    calf_left: metric.calfLeft || null,
    calf_right: metric.calfRight || null,
    thigh_left: metric.thighLeft || null,
    thigh_right: metric.thighRight || null,
    proximal_thigh_left: metric.proximalThighLeft || null,
    proximal_thigh_right: metric.proximalThighRight || null,
    wrist_diameter: metric.wristDiameter || null,
    femur_diameter: metric.femurDiameter || null,
    humerus_diameter: metric.humerusDiameter || null,
    composition_method: metric.compositionMethod || null,
    calc_protocol: metric.calcProtocol || null,
    skinfold_biceps: metric.skinfoldBiceps || null,
    skinfold_triceps: metric.skinfoldTriceps || null,
    skinfold_subscapular: metric.skinfoldSubscapular || null,
    skinfold_chest: metric.skinfoldChest || null,
    skinfold_midaxillary: metric.skinfoldMidaxillary || null,
    skinfold_suprailiac: metric.skinfoldSuprailiac || null,
    skinfold_supraspinal: metric.skinfoldSupraspinal || null,
    skinfold_abdominal: metric.skinfoldAbdominal || null,
    skinfold_thigh: metric.skinfoldThigh || null,
    skinfold_calf: metric.skinfoldCalf || null,
    photo_front: metric.photoFront || null,
    photo_back: metric.photoBack || null,
    photo_right: metric.photoRight || null,
    photo_left: metric.photoLeft || null,
    attachments: metric.attachments || [],
    observations: metric.observations || null,
  }
}
