ALTER TABLE custom_foods ADD COLUMN IF NOT EXISTS fibers_g NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE custom_foods ADD COLUMN IF NOT EXISTS sodium_mg NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE custom_foods ADD COLUMN IF NOT EXISTS allergens TEXT;

ALTER TABLE diet_plan_items ADD COLUMN IF NOT EXISTS fibers_g NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE diet_plan_items ADD COLUMN IF NOT EXISTS sodium_mg NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE diet_plan_items ADD COLUMN IF NOT EXISTS allergens TEXT;
