ALTER TABLE body_metrics ADD COLUMN IF NOT EXISTS gender TEXT;
ALTER TABLE body_metrics ADD COLUMN IF NOT EXISTS age INTEGER;
ALTER TABLE body_metrics ADD COLUMN IF NOT EXISTS height NUMERIC;
ALTER TABLE body_metrics ADD COLUMN IF NOT EXISTS activity_level TEXT;
ALTER TABLE body_metrics ADD COLUMN IF NOT EXISTS tmb NUMERIC;
ALTER TABLE body_metrics ADD COLUMN IF NOT EXISTS get NUMERIC;
