ALTER TABLE meal_logs ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '';
ALTER TABLE meal_logs ADD COLUMN IF NOT EXISTS calories REAL NOT NULL DEFAULT 0;
ALTER TABLE meal_logs ADD COLUMN IF NOT EXISTS protein REAL NOT NULL DEFAULT 0;
ALTER TABLE meal_logs ADD COLUMN IF NOT EXISTS carbs REAL NOT NULL DEFAULT 0;
ALTER TABLE meal_logs ADD COLUMN IF NOT EXISTS fat REAL NOT NULL DEFAULT 0;
ALTER TABLE meal_logs ADD COLUMN IF NOT EXISTS adherence TEXT NOT NULL DEFAULT 'perfect';
